#!/usr/bin/env node

var fs = require('fs');
var util = require('util');
var path = require('path');
var async = require('async');

var pull = require('./src/pull');

function main() {
  // Parse command line arguments.
  pull.parse(function(err,uid,key,sheet,works,outdir) {

    if (err) { // If we get an error while parsing, bail out.
      console.error(util.format('ERROR: %s',err));
      process.exit(1);
    }

    // Create the spreadsheet directory.
    var fullpath = path.join(outdir,sheet);
    fs.exists(fullpath,function(exists) {
      if (! exists) { fs.mkdirSync(fullpath); }

      // For each worksheet...
      async.each(works,function(work,call) {

        // Do the following in series...
        async.waterfall([

          // Pull specified worksheet from specified spreadsheet.
          function(call) {
            pull.pull(sheet,work,uid,key,call);
          },

          // Write worksheet to <sheet>/<work> as JSON.
          function(data,info,call) {
            var filepath = path.join(fullpath,info.worksheetTitle);
            pull.save(filepath,data,call);
          }

        ], call);

      },function(err) {
        if (err) { console.error(util.format('ERROR: %s',err)); }
      });
    });

  });
}

// Standalone invocation.
if (require.main === module) { main(); }
