#!/usr/bin/env node

var pull = require('./src/pull');

function usage() {
  // Resolve name of script.
  basename = require('path').basename(process.argv[1])

  // Print usage message.
  console.error("Usage:");
  console.error(require('util').format('  %s [<option>]* [<arg>]*',basename));
  console.error()
  console.error('Options:');
  console.error('  -h         : Print this help message.');
  console.error('  -k <key>   : Use specified private key.');
  console.error('  -u <user>  : Use specified username.');
  console.error('  -o <dir>   : Base directory for output.');
  console.error();
  console.error('Positional arguments:');
  console.error('  <ss>     : Spreadsheet to pull.');
  console.error('  [<ws>]+  : Worksheet(s) to pull.');
}

function check_args(args) {
  // Check parsed arguments for contents.

  // Check for help flag.
  if (args.h) {
    usage();
    process.exit(code=1);
  }

  // Check for key file.
  if (args.k === null) {
    console.error('ERROR: private key file must be specified');
    process.exit(code=1);
  }

  // Check for username.
  if (args.u === null) {
    console.error('ERROR: username must be specified');
    process.exit(code=1);
  }

  // Check that the spreadsheet has been specified.
  if (args._.length < 1) {
    console.error('ERROR: spreadsheet name must be specified');
    process.exit(code=1);
  }

  // Check that the worksheet
  if (args._.length < 2) {
    console.error('ERROR: one or most worksheet names must be specified');
    process.exit(code=1);
  }

  return;
}

function main() {
  // Parse command line arguments.
  var argv = require('minimist')(process.argv.slice(2));
  check_args(argv);

  var ss = argv._[0];
  var ws = argv._.slice(1);

  // Pull and save each worksheet specified.
  for (var i = 0; i < ws.length; ++i) {
    pull.pull(ss,ws[i],argv.u,argv.k,function(err,data,info) {
      if (err) { throw err; }
      pull.save('.',data,info,function(err) {
        if (err) { throw err; }
      });
    });
  }

  return;
}

// Standalone invocation.
if (require.main === module) { main(); }
